name: Deploy GitBook

on:
  push:
    branches:
      - main  # 或者 master，取决于您的默认分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g gitbook-cli
          gitbook install
          
      - name: Build GitBook
        run: |
          gitbook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: _book     # GitBook 构建输出目录